osx_image: xcode7
language: objective-c
notifications:
  email: false
script:
    #    - xcodebuild test -project HelloWorld.xcodeproj -scheme HelloWorld -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO | xcpretty -c && exit ${PIPESTATUS[0]}
    - echo $testing

